"""updates models 18

Revision ID: 1eca5813a250
Revises: d3d53604498b
Create Date: 2024-08-06 22:15:28.834964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1eca5813a250'
down_revision = 'd3d53604498b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_logs', schema=None) as batch_op:
        batch_op.alter_column('meal_type',
               existing_type=postgresql.ENUM('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_logs', schema=None) as batch_op:
        batch_op.alter_column('meal_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'),
               existing_nullable=False)

    # ### end Alembic commands ###
