"""updates models3

Revision ID: 2e6ebfd604a1
Revises: 0295720d1bc3
Create Date: 2024-07-30 23:54:45.611711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6ebfd604a1'
down_revision = '0295720d1bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protein', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fat', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nutrition_logs', schema=None) as batch_op:
        batch_op.drop_column('fat')
        batch_op.drop_column('protein')

    # ### end Alembic commands ###
