"""updates coach_name_2

Revision ID: 3542fcadb9e7
Revises: 48a714751d3a
Create Date: 2024-08-12 10:07:40.130568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3542fcadb9e7'
down_revision = '48a714751d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('coach_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('coach_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
