"""updates coach_name

Revision ID: 48a714751d3a
Revises: 2e0fd6f1d1a8
Create Date: 2024-08-12 09:43:49.359371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a714751d3a'
down_revision = '2e0fd6f1d1a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coach_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('coach_name')

    # ### end Alembic commands ###
