"""updates models16

Revision ID: 77edb8a484d8
Revises: a9949182b027
Create Date: 2024-08-06 15:31:55.456757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77edb8a484d8'
down_revision = 'a9949182b027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('target_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('target_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
