"""updates models4

Revision ID: b1b2f2794264
Revises: 2e6ebfd604a1
Create Date: 2024-07-31 12:46:27.502243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1b2f2794264'
down_revision = '2e6ebfd604a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_workout_plans_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coach_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_workouts_coach_id_coaches'), 'coaches', ['coach_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_workouts_coach_id_coaches'), type_='foreignkey')
        batch_op.drop_column('coach_id')

    with op.batch_alter_table('workout_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_workout_plans_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
